set(pblas_COMMON_SOURCES
    src/PB_CGatherV.c
    src/PB_CInOutV.c
    src/PB_CInOutV2.c
    src/PB_CInV.c
    src/PB_CInV2.c
    src/PB_COutV.c
    src/PB_CScatterV.c
    src/PB_CVMcontig.c
    src/PB_CVMinit.c
    src/PB_CVMloc.c
    src/PB_CVMnpq.c
    src/PB_CVMpack.c
    src/PB_CVMswp.c
    src/PB_CVMupdate.c
    src/PB_Cabort.c
    src/PB_Cainfog2l.c
    src/PB_CargFtoC.c
    src/PB_Cbinfo.c
    src/PB_Cchkmat.c
    src/PB_Cchkvec.c
    src/PB_Cconjg.c
    src/PB_Cdescribe.c
    src/PB_Cdescset.c
    src/PB_Cfirstnb.c
    src/PB_Cg2lrem.c
    src/PB_Cgcd.c
    src/PB_Cindxg2p.c
    src/PB_Cinfog2l.c
    src/PB_Citypeset.c
    src/PB_Clastnb.c
    src/PB_Clcm.c
    src/PB_Cnnxtroc.c
    src/PB_Cnpreroc.c
    src/PB_Cnumroc.c
    src/PB_Cpaxpby.c
    src/PB_CpaxpbyDN.c
    src/PB_CpaxpbyND.c
    src/PB_CpaxpbyNN.c
    src/PB_Cpdot11.c
    src/PB_CpdotND.c
    src/PB_CpdotNN.c
    src/PB_Cpgeadd.c
    src/PB_CpgemmAB.c
    src/PB_CpgemmAC.c
    src/PB_CpgemmBC.c
    src/PB_Cplacnjg.c
    src/PB_Cplapad.c
    src/PB_Cplapd2.c
    src/PB_Cplaprnt.c
    src/PB_Cplasca2.c
    src/PB_Cplascal.c
    src/PB_CpswapND.c
    src/PB_CpswapNN.c
    src/PB_Cpsym.c
    src/PB_CpsymmAB.c
    src/PB_CpsymmBC.c
    src/PB_Cpsyr.c
    src/PB_Cpsyr2.c
    src/PB_Cpsyr2kA.c
    src/PB_Cpsyr2kAC.c
    src/PB_CpsyrkA.c
    src/PB_CpsyrkAC.c
    src/PB_Cptradd.c
    src/PB_Cptran.c
    src/PB_Cptrm.c
    src/PB_CptrmmAB.c
    src/PB_CptrmmB.c
    src/PB_Cptrsm.c
    src/PB_CptrsmAB.c
    src/PB_CptrsmAB0.c
    src/PB_CptrsmAB1.c
    src/PB_CptrsmB.c
    src/PB_Cptrsv.c
    src/PB_Cspan.c
    src/PB_Ctzahemv.c
    src/PB_Ctzasymv.c
    src/PB_Ctzatrmv.c
    src/PB_Ctzhemm.c
    src/PB_Ctzhemv.c
    src/PB_Ctzher.c
    src/PB_Ctzher2.c
    src/PB_Ctzher2k.c
    src/PB_Ctzherk.c
    src/PB_Ctzsymm.c
    src/PB_Ctzsymv.c
    src/PB_Ctzsyr.c
    src/PB_Ctzsyr2.c
    src/PB_Ctzsyr2k.c
    src/PB_Ctzsyrk.c
    src/PB_Ctztrmm.c
    src/PB_Ctztrmv.c
    src/PB_Cwarn.c
    src/PB_freebuf_.c
    src/PB_topget_.c
    src/PB_topset_.c
    src/pilaenv.f
)

set(pblas_PRECISION_SOURCES
    src/PB_Cgetbuf.c
    src/PB_Cmalloc.c
    src/PB_Ctop.c
    src/pb_cetypeset.c
    src/pb_cytypeset.c
    src/peagemv_.c
    src/peamax_.c
    src/peasum_.c
    src/peasymv_.c
    src/peatrmv_.c
    src/peaxpy_.c
    src/pecopy_.c
    src/pedot_.c
    src/pegeadd_.c
    src/pegemm_.c
    src/pegemv_.c
    src/peger_.c
    src/penrm2_.c
    src/pescal_.c
    src/peswap_.c
    src/pesymm_.c
    src/pesymv_.c
    src/pesyr2_.c
    src/pesyr2k_.c
    src/pesyr_.c
    src/pesyrk_.c
    src/petradd_.c
    src/petran_.c
    src/petrmm_.c
    src/petrmv_.c
    src/petrsm_.c
    src/petrsv_.c
    src/peyasum_.c
    src/peynrm2_.c
    src/picopy_.c
    src/pyagemv_.c
    src/pyahemv_.c
    src/pyamax_.c
    src/pyatrmv_.c
    src/pyaxpy_.c
    src/pycopy_.c
    src/pydotc_.c
    src/pydotu_.c
    src/pyescal_.c
    src/pygeadd_.c
    src/pygemm_.c
    src/pygemv_.c
    src/pygerc_.c
    src/pygeru_.c
    src/pyhemm_.c
    src/pyhemv_.c
    src/pyher2_.c
    src/pyher2k_.c
    src/pyher_.c
    src/pyherk_.c
    src/pyscal_.c
    src/pyswap_.c
    src/pysymm_.c
    src/pysyr2k_.c
    src/pysyrk_.c
    src/pytradd_.c
    src/pytranc_.c
    src/pytranu_.c
    src/pytrmm_.c
    src/pytrmv_.c
    src/pytrsm_.c
    src/pytrsv_.c
)

set(pblas_DUAL_INTERFACE_SOURCES
    
)

set(pblas_LANGUAGE c)
