set(xblas_COMMON_SOURCES
    src/BLAS_error.c
    src/BLAS_fpinfo_x.c
)

set(xblas_PRECISION_SOURCES
    src/BLAS_fpinfo_x-f2c.c
    src/blas_eaxpby_x-f2c.c
    src/blas_eaxpby_x.c
    src/blas_edot_x-f2c.c
    src/blas_edot_x.c
    src/blas_egbmv2_x-f2c.c
    src/blas_egbmv2_x.c
    src/blas_egbmv_x-f2c.c
    src/blas_egbmv_x.c
    src/blas_ege_sum_mv_x-f2c.c
    src/blas_ege_sum_mv_x.c
    src/blas_egemm_x-f2c.c
    src/blas_egemm_x.c
    src/blas_egemv2_x-f2c.c
    src/blas_egemv2_x.c
    src/blas_egemv_x-f2c.c
    src/blas_egemv_x.c
    src/blas_esbmv_x-f2c.c
    src/blas_esbmv_x.c
    src/blas_espmv_x-f2c.c
    src/blas_espmv_x.c
    src/blas_esum_x-f2c.c
    src/blas_esum_x.c
    src/blas_esymm_x-f2c.c
    src/blas_esymm_x.c
    src/blas_esymv2_x-f2c.c
    src/blas_esymv2_x.c
    src/blas_esymv_x-f2c.c
    src/blas_esymv_x.c
    src/blas_etbsv_x-f2c.c
    src/blas_etbsv_x.c
    src/blas_etpmv_x-f2c.c
    src/blas_etpmv_x.c
    src/blas_etrmv_x-f2c.c
    src/blas_etrmv_x.c
    src/blas_etrsv_x-f2c.c
    src/blas_etrsv_x.c
    src/blas_ewaxpby_x-f2c.c
    src/blas_ewaxpby_x.c
    src/blas_malloc.c
    src/blas_yaxpby_x-f2c.c
    src/blas_yaxpby_x.c
    src/blas_ydot_x-f2c.c
    src/blas_ydot_x.c
    src/blas_ygbmv2_x-f2c.c
    src/blas_ygbmv2_x.c
    src/blas_ygbmv_x-f2c.c
    src/blas_ygbmv_x.c
    src/blas_yge_sum_mv_x-f2c.c
    src/blas_yge_sum_mv_x.c
    src/blas_ygemm_x-f2c.c
    src/blas_ygemm_x.c
    src/blas_ygemv2_x-f2c.c
    src/blas_ygemv2_x.c
    src/blas_ygemv_x-f2c.c
    src/blas_ygemv_x.c
    src/blas_yhbmv_x-f2c.c
    src/blas_yhbmv_x.c
    src/blas_yhemm_x-f2c.c
    src/blas_yhemm_x.c
    src/blas_yhemv2_x-f2c.c
    src/blas_yhemv2_x.c
    src/blas_yhemv_x-f2c.c
    src/blas_yhemv_x.c
    src/blas_yhpmv_x-f2c.c
    src/blas_yhpmv_x.c
    src/blas_ysbmv_x-f2c.c
    src/blas_ysbmv_x.c
    src/blas_yspmv_x-f2c.c
    src/blas_yspmv_x.c
    src/blas_ysum_x-f2c.c
    src/blas_ysum_x.c
    src/blas_ysymm_x-f2c.c
    src/blas_ysymm_x.c
    src/blas_ysymv2_x-f2c.c
    src/blas_ysymv2_x.c
    src/blas_ysymv_x-f2c.c
    src/blas_ysymv_x.c
    src/blas_ytbsv_x-f2c.c
    src/blas_ytbsv_x.c
    src/blas_ytpmv_x-f2c.c
    src/blas_ytpmv_x.c
    src/blas_ytrmv_x-f2c.c
    src/blas_ytrmv_x.c
    src/blas_ytrsv_x-f2c.c
    src/blas_ytrsv_x.c
    src/blas_ywaxpby_x-f2c.c
    src/blas_ywaxpby_x.c
)

set(xblas_DUAL_INTERFACE_SOURCES
    
)

set(xblas_LANGUAGE c)
