# Generated by: python -m migrator stage --target kind10
set(TARGET_NAME "kind10")
set(LIB_PREFIX "e")
set(LIB_PREFIX_COMPLEX "y")
set(NEEDS_MULTIFLOATS FALSE)
set(C_AS_CXX FALSE)
set(MF_HELPERS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/_helpers")
set(STAGED_LIBRARIES blas;xblas;blacs;lapack;ptzblas;scalapack_tools;pbblas;pblas;scalapack;scalapack_c;mumps)
