set(scalapack_COMMON_SOURCES
    src/pilaver.f
    src/piparmq.f
    src/pmpcol.f
    src/pmpim2.f
)

set(scalapack_PRECISION_SOURCES
    src/SL_init.f
    src/belaapp.f
    src/belaexc.f
    src/betrexc.f
    src/chk1mat.f
    src/dddot.f
    src/desc_convert.f
    src/descinit.f
    src/descset.f
    src/dsasum.f
    src/dscasum.f
    src/dscnrm2.f
    src/dsnrm2.f
    src/edbtf2.f
    src/edbtrf.f
    src/edttrf.f
    src/edttrsv.f
    src/elamsh.f
    src/elapst.f
    src/elaqr6.f
    src/elar1va.f
    src/elaref.f
    src/elarrb2.f
    src/elarrd2.f
    src/elarre2.f
    src/elarre2a.f
    src/elarrf2.f
    src/elarrv2.f
    src/elasorte.f
    src/elasrt2.f
    src/elatcpy.f
    src/ematadd.f
    src/epttrsv.f
    src/esdot.f
    src/estegr2.f
    src/estegr2a.f
    src/estegr2b.f
    src/estein2.f
    src/esteqr2.f
    src/etrmvt.f
    src/ilacpy.f
    src/indxg2l.f
    src/indxg2p.f
    src/indxl2g.f
    src/infog1l.f
    src/infog2l.f
    src/npreroc.f
    src/pchkxmat.f
    src/pechekpad.f
    src/pecol2row.f
    src/pedbsv.f
    src/pedbtrf.f
    src/pedbtrs.f
    src/pedbtrsv.f
    src/pedtsv.f
    src/pedttrf.f
    src/pedttrs.f
    src/pedttrsv.f
    src/peelget.f
    src/peelset.f
    src/peelset2.f
    src/pefillpad.f
    src/pegbsv.f
    src/pegbtrf.f
    src/pegbtrs.f
    src/pegebal.f
    src/pegebd2.f
    src/pegebrd.f
    src/pegecon.f
    src/pegeequ.f
    src/pegehd2.f
    src/pegehrd.f
    src/pegelq2.f
    src/pegelqf.f
    src/pegels.f
    src/pegeql2.f
    src/pegeqlf.f
    src/pegeqpf.f
    src/pegeqr2.f
    src/pegeqrf.f
    src/pegerfs.f
    src/pegerq2.f
    src/pegerqf.f
    src/pegesv.f
    src/pegesvd.f
    src/pegesvx.f
    src/pegetf2.f
    src/pegetrf.f
    src/pegetri.f
    src/pegetrs.f
    src/peggqrf.f
    src/peggrqf.f
    src/pehseqr.f
    src/pelabad.f
    src/pelabrd.f
    src/pelacon.f
    src/pelaconsb.f
    src/pelacp2.f
    src/pelacp3.f
    src/pelacpy.f
    src/pelaed0.f
    src/pelaed1.f
    src/pelaed2.f
    src/pelaed3.f
    src/pelaedz.f
    src/pelaevswp.f
    src/pelahqr.f
    src/pelahrd.f
    src/pelamch.f
    src/pelamr1d.f
    src/pelamve.f
    src/pelange.f
    src/pelanhs.f
    src/pelansy.f
    src/pelantr.f
    src/pelapiv.f
    src/pelaprnt.f
    src/pelapv2.f
    src/pelaqge.f
    src/pelaqr0.f
    src/pelaqr1.f
    src/pelaqr2.f
    src/pelaqr3.f
    src/pelaqr4.f
    src/pelaqr5.f
    src/pelaqsy.f
    src/pelaread.f
    src/pelared1d.f
    src/pelared2d.f
    src/pelarf.f
    src/pelarfb.f
    src/pelarfg.f
    src/pelarft.f
    src/pelarz.f
    src/pelarzb.f
    src/pelarzt.f
    src/pelascl.f
    src/pelase2.f
    src/pelaset.f
    src/pelasmsub.f
    src/pelasrt.f
    src/pelassq.f
    src/pelaswp.f
    src/pelatra.f
    src/pelatrd.f
    src/pelatrs.f
    src/pelatrz.f
    src/pelauu2.f
    src/pelauum.f
    src/pelawil.f
    src/pelawrite.f
    src/pematadd.f
    src/peorg2l.f
    src/peorg2r.f
    src/peorgl2.f
    src/peorglq.f
    src/peorgql.f
    src/peorgqr.f
    src/peorgr2.f
    src/peorgrq.f
    src/peorm2l.f
    src/peorm2r.f
    src/peormbr.f
    src/peormhr.f
    src/peorml2.f
    src/peormlq.f
    src/peormql.f
    src/peormqr.f
    src/peormr2.f
    src/peormr3.f
    src/peormrq.f
    src/peormrz.f
    src/peormtr.f
    src/pepbsv.f
    src/pepbtrf.f
    src/pepbtrs.f
    src/pepbtrsv.f
    src/pepocon.f
    src/pepoequ.f
    src/peporfs.f
    src/peposv.f
    src/peposvx.f
    src/pepotf2.f
    src/pepotrf.f
    src/pepotri.f
    src/pepotrs.f
    src/peptsv.f
    src/pepttrf.f
    src/pepttrs.f
    src/pepttrsv.f
    src/perot.f
    src/perow2col.f
    src/perscl.f
    src/pestebz.f
    src/pestedc.f
    src/pestein.f
    src/pesyev.f
    src/pesyevd.f
    src/pesyevr.f
    src/pesyevx.f
    src/pesygs2.f
    src/pesygst.f
    src/pesygvx.f
    src/pesyngst.f
    src/pesyntrd.f
    src/pesytd2.f
    src/pesytrd.f
    src/pesyttrd.f
    src/petrcon.f
    src/petreecomb.f
    src/petrord.f
    src/petrrfs.f
    src/petrsen.f
    src/petrti2.f
    src/petrtri.f
    src/petrtrs.f
    src/petzrzf.f
    src/peysum1.f
    src/pichekpad.f
    src/picol2row.f
    src/pielget.f
    src/pielset.f
    src/pielset2.f
    src/pifillpad.f
    src/pilaenvx_ep.f
    src/pilaprnt.f
    src/pirow2col.f
    src/pitreecomb.f
    src/pjlaenv_ep.f
    src/pychekpad.f
    src/pycol2row.f
    src/pydbsv.f
    src/pydbtrf.f
    src/pydbtrs.f
    src/pydbtrsv.f
    src/pydtsv.f
    src/pydttrf.f
    src/pydttrs.f
    src/pydttrsv.f
    src/pyelget.f
    src/pyelset.f
    src/pyelset2.f
    src/pyerscl.f
    src/pyfillpad.f
    src/pygbsv.f
    src/pygbtrf.f
    src/pygbtrs.f
    src/pygebd2.f
    src/pygebrd.f
    src/pygecon.f
    src/pygeequ.f
    src/pygehd2.f
    src/pygehrd.f
    src/pygelq2.f
    src/pygelqf.f
    src/pygels.f
    src/pygeql2.f
    src/pygeqlf.f
    src/pygeqpf.f
    src/pygeqr2.f
    src/pygeqrf.f
    src/pygerfs.f
    src/pygerq2.f
    src/pygerqf.f
    src/pygesv.f
    src/pygesvd.f
    src/pygesvx.f
    src/pygetf2.f
    src/pygetrf.f
    src/pygetri.f
    src/pygetrs.f
    src/pyggqrf.f
    src/pyggrqf.f
    src/pyheev.f
    src/pyheevd.f
    src/pyheevr.f
    src/pyheevx.f
    src/pyhegs2.f
    src/pyhegst.f
    src/pyhegvx.f
    src/pyhengst.f
    src/pyhentrd.f
    src/pyhetd2.f
    src/pyhetrd.f
    src/pyhettrd.f
    src/pylabrd.f
    src/pylacgv.f
    src/pylacon.f
    src/pylaconsb.f
    src/pylacp2.f
    src/pylacp3.f
    src/pylacpy.f
    src/pylaevswp.f
    src/pylahqr.f
    src/pylahrd.f
    src/pylamr1d.f
    src/pylange.f
    src/pylanhe.f
    src/pylanhs.f
    src/pylansy.f
    src/pylantr.f
    src/pylapiv.f
    src/pylaprnt.f
    src/pylapv2.f
    src/pylaqge.f
    src/pylaqsy.f
    src/pylaread.f
    src/pylarf.f
    src/pylarfb.f
    src/pylarfc.f
    src/pylarfg.f
    src/pylarft.f
    src/pylarz.f
    src/pylarzb.f
    src/pylarzc.f
    src/pylarzt.f
    src/pylascl.f
    src/pylase2.f
    src/pylaset.f
    src/pylasmsub.f
    src/pylassq.f
    src/pylaswp.f
    src/pylatra.f
    src/pylatrd.f
    src/pylatrs.f
    src/pylatrz.f
    src/pylattrs.f
    src/pylauu2.f
    src/pylauum.f
    src/pylawil.f
    src/pylawrite.f
    src/pymatadd.f
    src/pymax1.f
    src/pypbsv.f
    src/pypbtrf.f
    src/pypbtrs.f
    src/pypbtrsv.f
    src/pypocon.f
    src/pypoequ.f
    src/pyporfs.f
    src/pyposv.f
    src/pyposvx.f
    src/pypotf2.f
    src/pypotrf.f
    src/pypotri.f
    src/pypotrs.f
    src/pyptsv.f
    src/pypttrf.f
    src/pypttrs.f
    src/pypttrsv.f
    src/pyrow2col.f
    src/pystein.f
    src/pytrcon.f
    src/pytreecomb.f
    src/pytrevc.f
    src/pytrrfs.f
    src/pytrti2.f
    src/pytrtri.f
    src/pytrtrs.f
    src/pytzrzf.f
    src/pyung2l.f
    src/pyung2r.f
    src/pyungl2.f
    src/pyunglq.f
    src/pyungql.f
    src/pyungqr.f
    src/pyungr2.f
    src/pyungrq.f
    src/pyunm2l.f
    src/pyunm2r.f
    src/pyunmbr.f
    src/pyunmhr.f
    src/pyunml2.f
    src/pyunmlq.f
    src/pyunmql.f
    src/pyunmqr.f
    src/pyunmr2.f
    src/pyunmr3.f
    src/pyunmrq.f
    src/pyunmrz.f
    src/pyunmtr.f
    src/sltimer.f
    src/ydbtf2.f
    src/ydbtrf.f
    src/ydttrf.f
    src/ydttrsv.f
    src/ylahqr2.f
    src/ylamsh.f
    src/ylanv2.f
    src/ylaref.f
    src/ylatcpy.f
    src/ymatadd.f
    src/ypttrsv.f
    src/ysteqr2.f
    src/ytrmvt.f
    src/yydotc.f
    src/yydotu.f
)

set(scalapack_DUAL_INTERFACE_SOURCES
    
)

set(scalapack_LANGUAGE fortran)
