set(lapack_COMMON_SOURCES
    src/eisnan.f
    src/elaisnan.f
    src/la_constants_ep.F90
    src/la_xisnan_ep.F90
)

set(lapack_PRECISION_SOURCES
    src/ebbcsd.f
    src/ebdsdc.f
    src/ebdsqr.f
    src/ebdsvdx.f
    src/edisna.f
    src/egbbrd.f
    src/egbcon.f
    src/egbequ.f
    src/egbequb.f
    src/egbrfs.f
    src/egbrfsx.f
    src/egbsv.f
    src/egbsvx.f
    src/egbsvxx.f
    src/egbtf2.f
    src/egbtrf.f
    src/egbtrs.f
    src/egebak.f
    src/egebal.f
    src/egebd2.f
    src/egebrd.f
    src/egecon.f
    src/egedmd.f90
    src/egedmdq.f90
    src/egeequ.f
    src/egeequb.f
    src/egees.f
    src/egeesx.f
    src/egeev.f
    src/egeevx.f
    src/egehd2.f
    src/egehrd.f
    src/egejsv.f
    src/egelq.f
    src/egelq2.f
    src/egelqf.f
    src/egelqt.f
    src/egelqt3.f
    src/egels.f
    src/egelsd.f
    src/egelss.f
    src/egelst.f
    src/egelsy.f
    src/egemlq.f
    src/egemlqt.f
    src/egemqr.f
    src/egemqrt.f
    src/egeql2.f
    src/egeqlf.f
    src/egeqp3.f
    src/egeqp3rk.f
    src/egeqr.f
    src/egeqr2.f
    src/egeqr2p.f
    src/egeqrf.f
    src/egeqrfp.f
    src/egeqrt.f
    src/egeqrt2.f
    src/egeqrt3.f
    src/egerfs.f
    src/egerfsx.f
    src/egerq2.f
    src/egerqf.f
    src/egesc2.f
    src/egesdd.f
    src/egesv.f
    src/egesvd.f
    src/egesvdq.f
    src/egesvdx.f
    src/egesvj.f
    src/egesvx.f
    src/egesvxx.f
    src/egetc2.f
    src/egetf2.f
    src/egetrf.f
    src/egetrf2.f
    src/egetri.f
    src/egetrs.f
    src/egetsls.f
    src/egetsqrhrt.f
    src/eggbak.f
    src/eggbal.f
    src/egges.f
    src/egges3.f
    src/eggesx.f
    src/eggev.f
    src/eggev3.f
    src/eggevx.f
    src/eggglm.f
    src/egghd3.f
    src/egghrd.f
    src/egglse.f
    src/eggqrf.f
    src/eggrqf.f
    src/eggsvd3.f
    src/eggsvp3.f
    src/egsvj0.f
    src/egsvj1.f
    src/egtcon.f
    src/egtrfs.f
    src/egtsv.f
    src/egtsvx.f
    src/egttrf.f
    src/egttrs.f
    src/egtts2.f
    src/ehgeqz.f
    src/ehsein.f
    src/ehseqr.f
    src/ela_gbamv.f
    src/ela_gbrcond.f
    src/ela_gbrfsx_extended.f
    src/ela_gbrpvgrw.f
    src/ela_geamv.f
    src/ela_gercond.f
    src/ela_gerfsx_extended.f
    src/ela_gerpvgrw.f
    src/ela_lin_berr.f
    src/ela_porcond.f
    src/ela_porfsx_extended.f
    src/ela_porpvgrw.f
    src/ela_syamv.f
    src/ela_syrcond.f
    src/ela_syrfsx_extended.f
    src/ela_syrpvgrw.f
    src/ela_wwaddw.f
    src/elabad.f
    src/elabrd.f
    src/elacn2.f
    src/elacon.f
    src/elacpy.f
    src/eladiv.f
    src/elae2.f
    src/elaebz.f
    src/elaed0.f
    src/elaed1.f
    src/elaed2.f
    src/elaed3.f
    src/elaed4.f
    src/elaed5.f
    src/elaed6.f
    src/elaed7.f
    src/elaed8.f
    src/elaed9.f
    src/elaeda.f
    src/elaein.f
    src/elaev2.f
    src/elaexc.f
    src/elag2.f
    src/elags2.f
    src/elagtf.f
    src/elagtm.f
    src/elagts.f
    src/elagv2.f
    src/elahqr.f
    src/elahr2.f
    src/elaic1.f
    src/elaln2.f
    src/elals0.f
    src/elalsa.f
    src/elalsd.f
    src/elamch.f
    src/elamrg.f
    src/elamswlq.f
    src/elamtsqr.f
    src/elaneg.f
    src/elangb.f
    src/elange.f
    src/elangt.f
    src/elanhs.f
    src/elansb.f
    src/elansf.f
    src/elansp.f
    src/elanst.f
    src/elansy.f
    src/elantb.f
    src/elantp.f
    src/elantr.f
    src/elanv2.f
    src/elaorhr_col_getrfnp.f
    src/elaorhr_col_getrfnp2.f
    src/elapll.f
    src/elapmr.f
    src/elapmt.f
    src/elapy2.f
    src/elapy3.f
    src/elaqgb.f
    src/elaqge.f
    src/elaqp2.f
    src/elaqp2rk.f
    src/elaqp3rk.f
    src/elaqps.f
    src/elaqr0.f
    src/elaqr1.f
    src/elaqr2.f
    src/elaqr3.f
    src/elaqr4.f
    src/elaqr5.f
    src/elaqsb.f
    src/elaqsp.f
    src/elaqsy.f
    src/elaqtr.f
    src/elaqz0.f
    src/elaqz1.f
    src/elaqz2.f
    src/elaqz3.f
    src/elaqz4.f
    src/elar1v.f
    src/elar2v.f
    src/elarf.f
    src/elarf1f.f
    src/elarf1l.f
    src/elarfb.f
    src/elarfb_gett.f
    src/elarfg.f
    src/elarfgp.f
    src/elarft.f
    src/elarfx.f
    src/elarfy.f
    src/elargv.f
    src/elarmm.f
    src/elarnv.f
    src/elarra.f
    src/elarrb.f
    src/elarrc.f
    src/elarrd.f
    src/elarre.f
    src/elarrf.f
    src/elarrj.f
    src/elarrk.f
    src/elarrr.f
    src/elarrv.f
    src/elarscl2.f
    src/elartg.f90
    src/elartgp.f
    src/elartgs.f
    src/elartv.f
    src/elaruv.f
    src/elarz.f
    src/elarzb.f
    src/elarzt.f
    src/elas2.f
    src/elascl.f
    src/elascl2.f
    src/elasd0.f
    src/elasd1.f
    src/elasd2.f
    src/elasd3.f
    src/elasd4.f
    src/elasd5.f
    src/elasd6.f
    src/elasd7.f
    src/elasd8.f
    src/elasda.f
    src/elasdq.f
    src/elasdt.f
    src/elaset.f
    src/elasq1.f
    src/elasq2.f
    src/elasq3.f
    src/elasq4.f
    src/elasq5.f
    src/elasq6.f
    src/elasr.f
    src/elasrt.f
    src/elassq.f90
    src/elasv2.f
    src/elaswlq.f
    src/elaswp.f
    src/elasy2.f
    src/elasyf.f
    src/elasyf_aa.f
    src/elasyf_rk.f
    src/elasyf_rook.f
    src/elatbs.f
    src/elatdf.f
    src/elatps.f
    src/elatrd.f
    src/elatrs.f
    src/elatrs3.f
    src/elatrz.f
    src/elatsqr.f
    src/elauu2.f
    src/elauum.f
    src/eopgtr.f
    src/eopmtr.f
    src/eorbdb.f
    src/eorbdb1.f
    src/eorbdb2.f
    src/eorbdb3.f
    src/eorbdb4.f
    src/eorbdb5.f
    src/eorbdb6.f
    src/eorcsd.f
    src/eorcsd2by1.f
    src/eorg2l.f
    src/eorg2r.f
    src/eorgbr.f
    src/eorghr.f
    src/eorgl2.f
    src/eorglq.f
    src/eorgql.f
    src/eorgqr.f
    src/eorgr2.f
    src/eorgrq.f
    src/eorgtr.f
    src/eorgtsqr.f
    src/eorgtsqr_row.f
    src/eorhr_col.f
    src/eorm22.f
    src/eorm2l.f
    src/eorm2r.f
    src/eormbr.f
    src/eormhr.f
    src/eorml2.f
    src/eormlq.f
    src/eormql.f
    src/eormqr.f
    src/eormr2.f
    src/eormr3.f
    src/eormrq.f
    src/eormrz.f
    src/eormtr.f
    src/epbcon.f
    src/epbequ.f
    src/epbrfs.f
    src/epbstf.f
    src/epbsv.f
    src/epbsvx.f
    src/epbtf2.f
    src/epbtrf.f
    src/epbtrs.f
    src/epftrf.f
    src/epftri.f
    src/epftrs.f
    src/epocon.f
    src/epoequ.f
    src/epoequb.f
    src/eporfs.f
    src/eporfsx.f
    src/eposv.f
    src/eposvx.f
    src/eposvxx.f
    src/epotf2.f
    src/epotrf.f
    src/epotrf2.f
    src/epotri.f
    src/epotrs.f
    src/eppcon.f
    src/eppequ.f
    src/epprfs.f
    src/eppsv.f
    src/eppsvx.f
    src/epptrf.f
    src/epptri.f
    src/epptrs.f
    src/epstf2.f
    src/epstrf.f
    src/eptcon.f
    src/epteqr.f
    src/eptrfs.f
    src/eptsv.f
    src/eptsvx.f
    src/epttrf.f
    src/epttrs.f
    src/eptts2.f
    src/erscl.f
    src/esb2st_kernels.f
    src/esbev.f
    src/esbev_2stage.f
    src/esbevd.f
    src/esbevd_2stage.f
    src/esbevx.f
    src/esbevx_2stage.f
    src/esbgst.f
    src/esbgv.f
    src/esbgvd.f
    src/esbgvx.f
    src/esbtrd.f
    src/esfrk.f
    src/espcon.f
    src/espev.f
    src/espevd.f
    src/espevx.f
    src/espgst.f
    src/espgv.f
    src/espgvd.f
    src/espgvx.f
    src/esprfs.f
    src/espsv.f
    src/espsvx.f
    src/esptrd.f
    src/esptrf.f
    src/esptri.f
    src/esptrs.f
    src/estebz.f
    src/estedc.f
    src/estegr.f
    src/estein.f
    src/estemr.f
    src/esteqr.f
    src/esterf.f
    src/estev.f
    src/estevd.f
    src/estevr.f
    src/estevx.f
    src/esycon.f
    src/esycon_3.f
    src/esycon_rook.f
    src/esyconv.f
    src/esyconvf.f
    src/esyconvf_rook.f
    src/esyequb.f
    src/esyev.f
    src/esyev_2stage.f
    src/esyevd.f
    src/esyevd_2stage.f
    src/esyevr.f
    src/esyevr_2stage.f
    src/esyevx.f
    src/esyevx_2stage.f
    src/esygs2.f
    src/esygst.f
    src/esygv.f
    src/esygv_2stage.f
    src/esygvd.f
    src/esygvx.f
    src/esyrfs.f
    src/esyrfsx.f
    src/esysv.f
    src/esysv_aa.f
    src/esysv_aa_2stage.f
    src/esysv_rk.f
    src/esysv_rook.f
    src/esysvx.f
    src/esysvxx.f
    src/esyswapr.f
    src/esytd2.f
    src/esytf2.f
    src/esytf2_rk.f
    src/esytf2_rook.f
    src/esytrd.f
    src/esytrd_2stage.f
    src/esytrd_sb2st.F
    src/esytrd_sy2sb.f
    src/esytrf.f
    src/esytrf_aa.f
    src/esytrf_aa_2stage.f
    src/esytrf_rk.f
    src/esytrf_rook.f
    src/esytri.f
    src/esytri2.f
    src/esytri2x.f
    src/esytri_3.f
    src/esytri_3x.f
    src/esytri_rook.f
    src/esytrs.f
    src/esytrs2.f
    src/esytrs_3.f
    src/esytrs_aa.f
    src/esytrs_aa_2stage.f
    src/esytrs_rook.f
    src/etbcon.f
    src/etbrfs.f
    src/etbtrs.f
    src/etfsm.f
    src/etftri.f
    src/etfttp.f
    src/etfttr.f
    src/etgevc.f
    src/etgex2.f
    src/etgexc.f
    src/etgsen.f
    src/etgsja.f
    src/etgsna.f
    src/etgsy2.f
    src/etgsyl.f
    src/etpcon.f
    src/etplqt.f
    src/etplqt2.f
    src/etpmlqt.f
    src/etpmqrt.f
    src/etpqrt.f
    src/etpqrt2.f
    src/etprfb.f
    src/etprfs.f
    src/etptri.f
    src/etptrs.f
    src/etpttf.f
    src/etpttr.f
    src/etrcon.f
    src/etrevc.f
    src/etrevc3.f
    src/etrexc.f
    src/etrrfs.f
    src/etrsen.f
    src/etrsna.f
    src/etrsyl.f
    src/etrsyl3.f
    src/etrti2.f
    src/etrtri.f
    src/etrtrs.f
    src/etrttf.f
    src/etrttp.f
    src/etzrzf.f
    src/eysum1.f
    src/ilaelc.f
    src/ilaelr.f
    src/ilaenv2stage_ep.f
    src/ilaenv_ep.f
    src/ilaylc.f
    src/ilaylr.f
    src/iparam2stage_ep.F
    src/iymax1.f
    src/ybbcsd.f
    src/ybdsqr.f
    src/yerscl.f
    src/ygbbrd.f
    src/ygbcon.f
    src/ygbequ.f
    src/ygbequb.f
    src/ygbrfs.f
    src/ygbrfsx.f
    src/ygbsv.f
    src/ygbsvx.f
    src/ygbsvxx.f
    src/ygbtf2.f
    src/ygbtrf.f
    src/ygbtrs.f
    src/ygebak.f
    src/ygebal.f
    src/ygebd2.f
    src/ygebrd.f
    src/ygecon.f
    src/ygedmd.f90
    src/ygedmdq.f90
    src/ygeequ.f
    src/ygeequb.f
    src/ygees.f
    src/ygeesx.f
    src/ygeev.f
    src/ygeevx.f
    src/ygehd2.f
    src/ygehrd.f
    src/ygejsv.f
    src/ygelq.f
    src/ygelq2.f
    src/ygelqf.f
    src/ygelqt.f
    src/ygelqt3.f
    src/ygels.f
    src/ygelsd.f
    src/ygelss.f
    src/ygelst.f
    src/ygelsy.f
    src/ygemlq.f
    src/ygemlqt.f
    src/ygemqr.f
    src/ygemqrt.f
    src/ygeql2.f
    src/ygeqlf.f
    src/ygeqp3.f
    src/ygeqp3rk.f
    src/ygeqr.f
    src/ygeqr2.f
    src/ygeqr2p.f
    src/ygeqrf.f
    src/ygeqrfp.f
    src/ygeqrt.f
    src/ygeqrt2.f
    src/ygeqrt3.f
    src/ygerfs.f
    src/ygerfsx.f
    src/ygerq2.f
    src/ygerqf.f
    src/ygesc2.f
    src/ygesdd.f
    src/ygesv.f
    src/ygesvd.f
    src/ygesvdq.f
    src/ygesvdx.f
    src/ygesvj.f
    src/ygesvx.f
    src/ygesvxx.f
    src/ygetc2.f
    src/ygetf2.f
    src/ygetrf.f
    src/ygetrf2.f
    src/ygetri.f
    src/ygetrs.f
    src/ygetsls.f
    src/ygetsqrhrt.f
    src/yggbak.f
    src/yggbal.f
    src/ygges.f
    src/ygges3.f
    src/yggesx.f
    src/yggev.f
    src/yggev3.f
    src/yggevx.f
    src/yggglm.f
    src/ygghd3.f
    src/ygghrd.f
    src/ygglse.f
    src/yggqrf.f
    src/yggrqf.f
    src/yggsvd3.f
    src/yggsvp3.f
    src/ygsvj0.f
    src/ygsvj1.f
    src/ygtcon.f
    src/ygtrfs.f
    src/ygtsv.f
    src/ygtsvx.f
    src/ygttrf.f
    src/ygttrs.f
    src/ygtts2.f
    src/yhb2st_kernels.f
    src/yhbev.f
    src/yhbev_2stage.f
    src/yhbevd.f
    src/yhbevd_2stage.f
    src/yhbevx.f
    src/yhbevx_2stage.f
    src/yhbgst.f
    src/yhbgv.f
    src/yhbgvd.f
    src/yhbgvx.f
    src/yhbtrd.f
    src/yhecon.f
    src/yhecon_3.f
    src/yhecon_rook.f
    src/yheequb.f
    src/yheev.f
    src/yheev_2stage.f
    src/yheevd.f
    src/yheevd_2stage.f
    src/yheevr.f
    src/yheevr_2stage.f
    src/yheevx.f
    src/yheevx_2stage.f
    src/yhegs2.f
    src/yhegst.f
    src/yhegv.f
    src/yhegv_2stage.f
    src/yhegvd.f
    src/yhegvx.f
    src/yherfs.f
    src/yherfsx.f
    src/yhesv.f
    src/yhesv_aa.f
    src/yhesv_aa_2stage.f
    src/yhesv_rk.f
    src/yhesv_rook.f
    src/yhesvx.f
    src/yhesvxx.f
    src/yheswapr.f
    src/yhetd2.f
    src/yhetf2.f
    src/yhetf2_rk.f
    src/yhetf2_rook.f
    src/yhetrd.f
    src/yhetrd_2stage.f
    src/yhetrd_hb2st.F
    src/yhetrd_he2hb.f
    src/yhetrf.f
    src/yhetrf_aa.f
    src/yhetrf_aa_2stage.f
    src/yhetrf_rk.f
    src/yhetrf_rook.f
    src/yhetri.f
    src/yhetri2.f
    src/yhetri2x.f
    src/yhetri_3.f
    src/yhetri_3x.f
    src/yhetri_rook.f
    src/yhetrs.f
    src/yhetrs2.f
    src/yhetrs_3.f
    src/yhetrs_aa.f
    src/yhetrs_aa_2stage.f
    src/yhetrs_rook.f
    src/yhfrk.f
    src/yhgeqz.f
    src/yhpcon.f
    src/yhpev.f
    src/yhpevd.f
    src/yhpevx.f
    src/yhpgst.f
    src/yhpgv.f
    src/yhpgvd.f
    src/yhpgvx.f
    src/yhprfs.f
    src/yhpsv.f
    src/yhpsvx.f
    src/yhptrd.f
    src/yhptrf.f
    src/yhptri.f
    src/yhptrs.f
    src/yhsein.f
    src/yhseqr.f
    src/yla_gbamv.f
    src/yla_gbrcond_c.f
    src/yla_gbrcond_x.f
    src/yla_gbrfsx_extended.f
    src/yla_gbrpvgrw.f
    src/yla_geamv.f
    src/yla_gercond_c.f
    src/yla_gercond_x.f
    src/yla_gerfsx_extended.f
    src/yla_gerpvgrw.f
    src/yla_heamv.f
    src/yla_hercond_c.f
    src/yla_hercond_x.f
    src/yla_herfsx_extended.f
    src/yla_herpvgrw.f
    src/yla_lin_berr.f
    src/yla_porcond_c.f
    src/yla_porcond_x.f
    src/yla_porfsx_extended.f
    src/yla_porpvgrw.f
    src/yla_syamv.f
    src/yla_syrcond_c.f
    src/yla_syrcond_x.f
    src/yla_syrfsx_extended.f
    src/yla_syrpvgrw.f
    src/yla_wwaddw.f
    src/ylabrd.f
    src/ylacgv.f
    src/ylacn2.f
    src/ylacon.f
    src/ylacp2.f
    src/ylacpy.f
    src/ylacrm.f
    src/ylacrt.f
    src/yladiv.f
    src/ylaed0.f
    src/ylaed7.f
    src/ylaed8.f
    src/ylaein.f
    src/ylaesy.f
    src/ylaev2.f
    src/ylags2.f
    src/ylagtm.f
    src/ylahef.f
    src/ylahef_aa.f
    src/ylahef_rk.f
    src/ylahef_rook.f
    src/ylahqr.f
    src/ylahr2.f
    src/ylaic1.f
    src/ylals0.f
    src/ylalsa.f
    src/ylalsd.f
    src/ylamswlq.f
    src/ylamtsqr.f
    src/ylangb.f
    src/ylange.f
    src/ylangt.f
    src/ylanhb.f
    src/ylanhe.f
    src/ylanhf.f
    src/ylanhp.f
    src/ylanhs.f
    src/ylanht.f
    src/ylansb.f
    src/ylansp.f
    src/ylansy.f
    src/ylantb.f
    src/ylantp.f
    src/ylantr.f
    src/ylapll.f
    src/ylapmr.f
    src/ylapmt.f
    src/ylaqgb.f
    src/ylaqge.f
    src/ylaqhb.f
    src/ylaqhe.f
    src/ylaqhp.f
    src/ylaqp2.f
    src/ylaqp2rk.f
    src/ylaqp3rk.f
    src/ylaqps.f
    src/ylaqr0.f
    src/ylaqr1.f
    src/ylaqr2.f
    src/ylaqr3.f
    src/ylaqr4.f
    src/ylaqr5.f
    src/ylaqsb.f
    src/ylaqsp.f
    src/ylaqsy.f
    src/ylaqz0.f
    src/ylaqz1.f
    src/ylaqz2.f
    src/ylaqz3.f
    src/ylar1v.f
    src/ylar2v.f
    src/ylarcm.f
    src/ylarf.f
    src/ylarf1f.f
    src/ylarf1l.f
    src/ylarfb.f
    src/ylarfb_gett.f
    src/ylarfg.f
    src/ylarfgp.f
    src/ylarft.f
    src/ylarfx.f
    src/ylarfy.f
    src/ylargv.f
    src/ylarnv.f
    src/ylarrv.f
    src/ylarscl2.f
    src/ylartg.f90
    src/ylartv.f
    src/ylarz.f
    src/ylarzb.f
    src/ylarzt.f
    src/ylascl.f
    src/ylascl2.f
    src/ylaset.f
    src/ylasr.f
    src/ylassq.f90
    src/ylaswlq.f
    src/ylaswp.f
    src/ylasyf.f
    src/ylasyf_aa.f
    src/ylasyf_rk.f
    src/ylasyf_rook.f
    src/ylatbs.f
    src/ylatdf.f
    src/ylatps.f
    src/ylatrd.f
    src/ylatrs.f
    src/ylatrs3.f
    src/ylatrz.f
    src/ylatsqr.f
    src/ylaunhr_col_getrfnp.f
    src/ylaunhr_col_getrfnp2.f
    src/ylauu2.f
    src/ylauum.f
    src/ypbcon.f
    src/ypbequ.f
    src/ypbrfs.f
    src/ypbstf.f
    src/ypbsv.f
    src/ypbsvx.f
    src/ypbtf2.f
    src/ypbtrf.f
    src/ypbtrs.f
    src/ypftrf.f
    src/ypftri.f
    src/ypftrs.f
    src/ypocon.f
    src/ypoequ.f
    src/ypoequb.f
    src/yporfs.f
    src/yporfsx.f
    src/yposv.f
    src/yposvx.f
    src/yposvxx.f
    src/ypotf2.f
    src/ypotrf.f
    src/ypotrf2.f
    src/ypotri.f
    src/ypotrs.f
    src/yppcon.f
    src/yppequ.f
    src/ypprfs.f
    src/yppsv.f
    src/yppsvx.f
    src/ypptrf.f
    src/ypptri.f
    src/ypptrs.f
    src/ypstf2.f
    src/ypstrf.f
    src/yptcon.f
    src/ypteqr.f
    src/yptrfs.f
    src/yptsv.f
    src/yptsvx.f
    src/ypttrf.f
    src/ypttrs.f
    src/yptts2.f
    src/yrot.f
    src/yrscl.f
    src/yspcon.f
    src/yspmv.f
    src/yspr.f
    src/ysprfs.f
    src/yspsv.f
    src/yspsvx.f
    src/ysptrf.f
    src/ysptri.f
    src/ysptrs.f
    src/ystedc.f
    src/ystegr.f
    src/ystein.f
    src/ystemr.f
    src/ysteqr.f
    src/ysycon.f
    src/ysycon_3.f
    src/ysycon_rook.f
    src/ysyconv.f
    src/ysyconvf.f
    src/ysyconvf_rook.f
    src/ysyequb.f
    src/ysymv.f
    src/ysyr.f
    src/ysyrfs.f
    src/ysyrfsx.f
    src/ysysv.f
    src/ysysv_aa.f
    src/ysysv_aa_2stage.f
    src/ysysv_rk.f
    src/ysysv_rook.f
    src/ysysvx.f
    src/ysysvxx.f
    src/ysyswapr.f
    src/ysytf2.f
    src/ysytf2_rk.f
    src/ysytf2_rook.f
    src/ysytrf.f
    src/ysytrf_aa.f
    src/ysytrf_aa_2stage.f
    src/ysytrf_rk.f
    src/ysytrf_rook.f
    src/ysytri.f
    src/ysytri2.f
    src/ysytri2x.f
    src/ysytri_3.f
    src/ysytri_3x.f
    src/ysytri_rook.f
    src/ysytrs.f
    src/ysytrs2.f
    src/ysytrs_3.f
    src/ysytrs_aa.f
    src/ysytrs_aa_2stage.f
    src/ysytrs_rook.f
    src/ytbcon.f
    src/ytbrfs.f
    src/ytbtrs.f
    src/ytfsm.f
    src/ytftri.f
    src/ytfttp.f
    src/ytfttr.f
    src/ytgevc.f
    src/ytgex2.f
    src/ytgexc.f
    src/ytgsen.f
    src/ytgsja.f
    src/ytgsna.f
    src/ytgsy2.f
    src/ytgsyl.f
    src/ytpcon.f
    src/ytplqt.f
    src/ytplqt2.f
    src/ytpmlqt.f
    src/ytpmqrt.f
    src/ytpqrt.f
    src/ytpqrt2.f
    src/ytprfb.f
    src/ytprfs.f
    src/ytptri.f
    src/ytptrs.f
    src/ytpttf.f
    src/ytpttr.f
    src/ytrcon.f
    src/ytrevc.f
    src/ytrevc3.f
    src/ytrexc.f
    src/ytrrfs.f
    src/ytrsen.f
    src/ytrsna.f
    src/ytrsyl.f
    src/ytrsyl3.f
    src/ytrti2.f
    src/ytrtri.f
    src/ytrtrs.f
    src/ytrttf.f
    src/ytrttp.f
    src/ytzrzf.f
    src/yunbdb.f
    src/yunbdb1.f
    src/yunbdb2.f
    src/yunbdb3.f
    src/yunbdb4.f
    src/yunbdb5.f
    src/yunbdb6.f
    src/yuncsd.f
    src/yuncsd2by1.f
    src/yung2l.f
    src/yung2r.f
    src/yungbr.f
    src/yunghr.f
    src/yungl2.f
    src/yunglq.f
    src/yungql.f
    src/yungqr.f
    src/yungr2.f
    src/yungrq.f
    src/yungtr.f
    src/yungtsqr.f
    src/yungtsqr_row.f
    src/yunhr_col.f
    src/yunm22.f
    src/yunm2l.f
    src/yunm2r.f
    src/yunmbr.f
    src/yunmhr.f
    src/yunml2.f
    src/yunmlq.f
    src/yunmql.f
    src/yunmqr.f
    src/yunmr2.f
    src/yunmr3.f
    src/yunmrq.f
    src/yunmrz.f
    src/yunmtr.f
    src/yupgtr.f
    src/yupmtr.f
)

set(lapack_DUAL_INTERFACE_SOURCES
    
)

set(lapack_LANGUAGE fortran)
