set(ptzblas_COMMON_SOURCES
    src/immadd.f
    src/immdda.f
    src/immddat.f
    src/immtadd.f
    src/pxerbla.f
)

set(ptzblas_PRECISION_SOURCES
    src/eagemv.f
    src/eascal.f
    src/easqrtb.f
    src/easymv.f
    src/eatrmv.f
    src/ecshft.f
    src/emmadd.f
    src/emmcadd.f
    src/emmdda.f
    src/emmddac.f
    src/emmddact.f
    src/emmddat.f
    src/emmtadd.f
    src/emmtcadd.f
    src/ershft.f
    src/eset.f
    src/etzpad.f
    src/etzpadcpy.f
    src/etzscal.f
    src/evasum.f
    src/evvdot.f
    src/eyvasum.f
    src/yagemv.f
    src/yahemv.f
    src/yasymv.f
    src/yatrmv.f
    src/ycshft.f
    src/yhescal.f
    src/ymmadd.f
    src/ymmcadd.f
    src/ymmdda.f
    src/ymmddac.f
    src/ymmddact.f
    src/ymmddat.f
    src/ymmtadd.f
    src/ymmtcadd.f
    src/yrshft.f
    src/yset.f
    src/ysymv.f
    src/ysyr.f
    src/ysyr2.f
    src/ytzcnjg.f
    src/ytzpad.f
    src/ytzpadcpy.f
    src/ytzscal.f
    src/yvvdotc.f
    src/yvvdotu.f
    src/yydotc.f
    src/yydotu.f
)

set(ptzblas_DUAL_INTERFACE_SOURCES
    
)

set(ptzblas_LANGUAGE fortran)
