set(mumps_COMMON_SOURCES
    src/ana_orderings.F
    src/ana_orderings_wrappers_m.F
    src/bcast_errors.F
    src/double_linked_list.F
    src/estim_flops.F
    src/fac_future_niv2_mod.F
    src/lr_common.F
    src/lr_stats.F
    src/mumps_comm_buffer_common.F
    src/mumps_l0_omp_m.F
    src/mumps_load.F
    src/mumps_memory_mod.F
    src/mumps_ooc_common.F
    src/mumps_pivnul_mod.F
    src/mumps_static_mapping.F
    src/mumps_version.F
    src/tools_common.F
    src/tools_common_m.F
)

set(mumps_PRECISION_SOURCES
    src/EMUMPS_IXAMAX.F
    src/YMUMPS_IXAMAX.F
    src/ana_AMDMF.F
    src/ana_blk.F
    src/ana_blk_m.F
    src/ana_omp_m.F
    src/ana_set_ordering.F
    src/eana_LDLT_preprocess.F
    src/eana_aux.F
    src/eana_aux_ELT.F
    src/eana_aux_par.F
    src/eana_dist_m.F
    src/eana_driver.F
    src/eana_lr.F
    src/eana_mtrans.F
    src/eana_reordertree.F
    src/earrowheads.F
    src/ebcast_int.F
    src/eend_driver.F
    src/efac_asm.F
    src/efac_asm_ELT.F
    src/efac_asm_master_ELT_m.F
    src/efac_asm_master_m.F
    src/efac_b.F
    src/efac_compact_factors_m.F
    src/efac_determinant.F
    src/efac_diag.F
    src/efac_dist_arrowheads_omp.F
    src/efac_distrib_ELT.F
    src/efac_distrib_distentry.F
    src/efac_driver.F
    src/efac_front_LDLT_type1.F
    src/efac_front_LDLT_type2.F
    src/efac_front_LU_type1.F
    src/efac_front_LU_type2.F
    src/efac_front_aux.F
    src/efac_front_type2_aux.F
    src/efac_lastrtnelind.F
    src/efac_lr.F
    src/efac_mem_alloc_cb.F
    src/efac_mem_compress_cb.F
    src/efac_mem_dynamic.F
    src/efac_mem_free_block_cb.F
    src/efac_mem_stack.F
    src/efac_mem_stack_aux.F
    src/efac_omp_m.F
    src/efac_par_m.F
    src/efac_process_band.F
    src/efac_process_bf.F
    src/efac_process_blfac_slave.F
    src/efac_process_blocfacto.F
    src/efac_process_blocfacto_LDLT.F
    src/efac_process_contrib_type1.F
    src/efac_process_contrib_type2.F
    src/efac_process_contrib_type3.F
    src/efac_process_end_facto_slave.F
    src/efac_process_maprow.F
    src/efac_process_master2.F
    src/efac_process_message.F
    src/efac_process_root2slave.F
    src/efac_process_root2son.F
    src/efac_process_rtnelind.F
    src/efac_root_parallel.F
    src/efac_scalings.F
    src/efac_scalings_simScaleAbs.F
    src/efac_scalings_simScale_util.F
    src/efac_sispointers_m.F
    src/efac_sol_l0omp_m.F
    src/efac_sol_pool.F
    src/efac_type3_symmetrize.F
    src/eini_defaults.F
    src/eini_driver.F
    src/elr_core.F
    src/elr_type.F
    src/emumps_comm_buffer.F
    src/emumps_config_file.F
    src/emumps_driver.F
    src/emumps_f77.F
    src/emumps_intr_types.F
    src/emumps_lr_data_m.F
    src/emumps_mpi3_mod.F
    src/emumps_ooc.F
    src/emumps_ooc_buffer.F
    src/emumps_save_restore.F
    src/emumps_save_restore_files.F
    src/emumps_sol_es.F
    src/emumps_struc_def.F
    src/eol_common.F
    src/eol_ds_common_m.F
    src/eol_omp_common_m.F
    src/eomp_tps_m.F
    src/eooc_panel_piv.F
    src/erank_revealing.F
    src/esol_aux.F
    src/esol_bwd.F
    src/esol_bwd_aux.F
    src/esol_c.F
    src/esol_distrhs.F
    src/esol_distsol.F
    src/esol_driver.F
    src/esol_fwd.F
    src/esol_fwd_aux.F
    src/esol_lr.F
    src/esol_matvec.F
    src/esol_omp_m.F
    src/esol_root_parallel.F
    src/estatic_ptr_m.F
    src/etools.F
    src/etype3_root.F
    src/fac_asm_build_sort_index_ELT_m.F
    src/fac_asm_build_sort_index_m.F
    src/fac_descband_data_m.F
    src/fac_maprow_data_m.F
    src/front_data_mgt_m.F
    src/mumps_intr_types_common.F
    src/mumps_lr_stats_ep.F
    src/mumps_memory_mod_ep.F
    src/mumps_mpitoomp_m.F
    src/mumps_print_defined.F
    src/mumps_type2_blocking.F
    src/omp_tps_common_m.F
    src/yana_LDLT_preprocess.F
    src/yana_aux.F
    src/yana_aux_ELT.F
    src/yana_aux_par.F
    src/yana_dist_m.F
    src/yana_driver.F
    src/yana_lr.F
    src/yana_mtrans.F
    src/yana_reordertree.F
    src/yarrowheads.F
    src/ybcast_int.F
    src/yend_driver.F
    src/yfac_asm.F
    src/yfac_asm_ELT.F
    src/yfac_asm_master_ELT_m.F
    src/yfac_asm_master_m.F
    src/yfac_b.F
    src/yfac_compact_factors_m.F
    src/yfac_determinant.F
    src/yfac_diag.F
    src/yfac_dist_arrowheads_omp.F
    src/yfac_distrib_ELT.F
    src/yfac_distrib_distentry.F
    src/yfac_driver.F
    src/yfac_front_LDLT_type1.F
    src/yfac_front_LDLT_type2.F
    src/yfac_front_LU_type1.F
    src/yfac_front_LU_type2.F
    src/yfac_front_aux.F
    src/yfac_front_type2_aux.F
    src/yfac_lastrtnelind.F
    src/yfac_lr.F
    src/yfac_mem_alloc_cb.F
    src/yfac_mem_compress_cb.F
    src/yfac_mem_dynamic.F
    src/yfac_mem_free_block_cb.F
    src/yfac_mem_stack.F
    src/yfac_mem_stack_aux.F
    src/yfac_omp_m.F
    src/yfac_par_m.F
    src/yfac_process_band.F
    src/yfac_process_bf.F
    src/yfac_process_blfac_slave.F
    src/yfac_process_blocfacto.F
    src/yfac_process_blocfacto_LDLT.F
    src/yfac_process_contrib_type1.F
    src/yfac_process_contrib_type2.F
    src/yfac_process_contrib_type3.F
    src/yfac_process_end_facto_slave.F
    src/yfac_process_maprow.F
    src/yfac_process_master2.F
    src/yfac_process_message.F
    src/yfac_process_root2slave.F
    src/yfac_process_root2son.F
    src/yfac_process_rtnelind.F
    src/yfac_root_parallel.F
    src/yfac_scalings.F
    src/yfac_scalings_simScaleAbs.F
    src/yfac_scalings_simScale_util.F
    src/yfac_sispointers_m.F
    src/yfac_sol_l0omp_m.F
    src/yfac_sol_pool.F
    src/yfac_type3_symmetrize.F
    src/yini_defaults.F
    src/yini_driver.F
    src/ylr_core.F
    src/ylr_type.F
    src/ymumps_comm_buffer.F
    src/ymumps_config_file.F
    src/ymumps_driver.F
    src/ymumps_f77.F
    src/ymumps_intr_types.F
    src/ymumps_lr_data_m.F
    src/ymumps_mpi3_mod.F
    src/ymumps_ooc.F
    src/ymumps_ooc_buffer.F
    src/ymumps_save_restore.F
    src/ymumps_save_restore_files.F
    src/ymumps_sol_es.F
    src/ymumps_struc_def.F
    src/yomp_tps_m.F
    src/yooc_panel_piv.F
    src/yrank_revealing.F
    src/ysol_aux.F
    src/ysol_bwd.F
    src/ysol_bwd_aux.F
    src/ysol_c.F
    src/ysol_distrhs.F
    src/ysol_distsol.F
    src/ysol_driver.F
    src/ysol_fwd.F
    src/ysol_fwd_aux.F
    src/ysol_lr.F
    src/ysol_matvec.F
    src/ysol_omp_m.F
    src/ysol_root_parallel.F
    src/ystatic_ptr_m.F
    src/ytools.F
    src/ytype3_root.F
)

set(mumps_DUAL_INTERFACE_SOURCES
    
)

set(mumps_LANGUAGE fortran)
