set(blacs_COMMON_SOURCES
    src/BI_Arecv.c
    src/BI_ArgCheck.c
    src/BI_Asend.c
    src/BI_BeComb.c
    src/BI_BlacsAbort.c
    src/BI_BlacsErr.c
    src/BI_BlacsWarn.c
    src/BI_BuffIsFree.c
    src/BI_ContxtNum.c
    src/BI_EmergencyBuff.c
    src/BI_GetMpiGeType.c
    src/BI_GetMpiTrType.c
    src/BI_HypBR.c
    src/BI_HypBS.c
    src/BI_IdringBR.c
    src/BI_IdringBS.c
    src/BI_MpathBR.c
    src/BI_MpathBS.c
    src/BI_MringComb.c
    src/BI_Rsend.c
    src/BI_Srecv.c
    src/BI_SringBR.c
    src/BI_SringBS.c
    src/BI_Ssend.c
    src/BI_TransDist.c
    src/BI_TreeBR.c
    src/BI_TreeBS.c
    src/BI_TreeComb.c
    src/BI_Unpack.c
    src/BI_UpdateBuffs.c
    src/BI_iMPI_amn.c
    src/BI_iMPI_amn2.c
    src/BI_iMPI_amx.c
    src/BI_iMPI_amx2.c
    src/BI_imvcopy.c
    src/BI_ivmcopy.c
    src/BI_ivvamn.c
    src/BI_ivvamn2.c
    src/BI_ivvamx.c
    src/BI_ivvamx2.c
    src/BI_ivvsum.c
    src/blacs_abort_.c
    src/blacs_exit_.c
    src/blacs_get_.c
    src/blacs_pcoord_.c
    src/blacs_pinfo_.c
    src/blacs_pnum_.c
    src/blacs_set_.c
    src/blacs_setup_.c
)

set(blacs_PRECISION_SOURCES
    src/BI_GetBuff.c
    src/BI_GlobalVars.c
    src/BI_Pack.c
    src/BI_TransUserComm.c
    src/BI_cMPI_amn.c
    src/BI_cMPI_amn2.c
    src/BI_cMPI_amx.c
    src/BI_cMPI_amx2.c
    src/BI_cMPI_sum.c
    src/BI_cvvamn.c
    src/BI_cvvamn2.c
    src/BI_cvvamx.c
    src/BI_cvvamx2.c
    src/BI_cvvsum.c
    src/BI_eMPI_amn.c
    src/BI_eMPI_amn2.c
    src/BI_eMPI_amx.c
    src/BI_eMPI_amx2.c
    src/BI_eMPI_sum.c
    src/BI_emvcopy.c
    src/BI_evmcopy.c
    src/BI_evvamn.c
    src/BI_evvamn2.c
    src/BI_evvamx.c
    src/BI_evvamx2.c
    src/BI_evvsum.c
    src/BI_sMPI_amn.c
    src/BI_sMPI_amn2.c
    src/BI_sMPI_amx.c
    src/BI_sMPI_amx2.c
    src/BI_smvcopy.c
    src/BI_svmcopy.c
    src/BI_svvamn.c
    src/BI_svvamn2.c
    src/BI_svvamx.c
    src/BI_svvamx2.c
    src/BI_svvsum.c
    src/BI_yMPI_amn.c
    src/BI_yMPI_amn2.c
    src/BI_yMPI_amx.c
    src/BI_yMPI_amx2.c
    src/BI_yMPI_sum.c
    src/BI_yvvamn.c
    src/BI_yvvamn2.c
    src/BI_yvvamx.c
    src/BI_yvvamx2.c
    src/BI_yvvsum.c
    src/blacs2sys_.c
    src/blacs_barr_.c
    src/blacs_free_.c
    src/blacs_grid_.c
    src/blacs_info_.c
    src/blacs_init_.c
    src/blacs_map_.c
    src/cgamn2d_.c
    src/cgamx2d_.c
    src/cgebr2d_.c
    src/cgebs2d_.c
    src/cgerv2d_.c
    src/cgesd2d_.c
    src/cgsum2d_.c
    src/ctrbr2d_.c
    src/ctrbs2d_.c
    src/ctrrv2d_.c
    src/ctrsd2d_.c
    src/ecputime00_.c
    src/egamn2d_.c
    src/egamx2d_.c
    src/egebr2d_.c
    src/egebs2d_.c
    src/egerv2d_.c
    src/egesd2d_.c
    src/egsum2d_.c
    src/etrbr2d_.c
    src/etrbs2d_.c
    src/etrrv2d_.c
    src/etrsd2d_.c
    src/ewalltime00_.c
    src/free_handle_.c
    src/igamn2d_.c
    src/igamx2d_.c
    src/igebr2d_.c
    src/igebs2d_.c
    src/igerv2d_.c
    src/igesd2d_.c
    src/igsum2d_.c
    src/itrbr2d_.c
    src/itrbs2d_.c
    src/itrrv2d_.c
    src/itrsd2d_.c
    src/kbrid_.c
    src/kbsid_.c
    src/krecvid_.c
    src/ksendid_.c
    src/sgamn2d_.c
    src/sgamx2d_.c
    src/sgebr2d_.c
    src/sgebs2d_.c
    src/sgerv2d_.c
    src/sgesd2d_.c
    src/sgsum2d_.c
    src/strbr2d_.c
    src/strbs2d_.c
    src/strrv2d_.c
    src/strsd2d_.c
    src/sys2blacs_.c
    src/ygamn2d_.c
    src/ygamx2d_.c
    src/ygebr2d_.c
    src/ygebs2d_.c
    src/ygerv2d_.c
    src/ygesd2d_.c
    src/ygsum2d_.c
    src/ytrbr2d_.c
    src/ytrbs2d_.c
    src/ytrrv2d_.c
    src/ytrsd2d_.c
)

set(blacs_DUAL_INTERFACE_SOURCES
    src/blacs2sys_.c
    src/blacs_abort_.c
    src/blacs_barr_.c
    src/blacs_exit_.c
    src/blacs_free_.c
    src/blacs_get_.c
    src/blacs_grid_.c
    src/blacs_info_.c
    src/blacs_init_.c
    src/blacs_map_.c
    src/blacs_pcoord_.c
    src/blacs_pinfo_.c
    src/blacs_pnum_.c
    src/blacs_set_.c
    src/blacs_setup_.c
    src/cgamn2d_.c
    src/cgamx2d_.c
    src/cgebr2d_.c
    src/cgebs2d_.c
    src/cgerv2d_.c
    src/cgesd2d_.c
    src/cgsum2d_.c
    src/ctrbr2d_.c
    src/ctrbs2d_.c
    src/ctrrv2d_.c
    src/ctrsd2d_.c
    src/ecputime00_.c
    src/egamn2d_.c
    src/egamx2d_.c
    src/egebr2d_.c
    src/egebs2d_.c
    src/egerv2d_.c
    src/egesd2d_.c
    src/egsum2d_.c
    src/etrbr2d_.c
    src/etrbs2d_.c
    src/etrrv2d_.c
    src/etrsd2d_.c
    src/ewalltime00_.c
    src/free_handle_.c
    src/igamn2d_.c
    src/igamx2d_.c
    src/igebr2d_.c
    src/igebs2d_.c
    src/igerv2d_.c
    src/igesd2d_.c
    src/igsum2d_.c
    src/itrbr2d_.c
    src/itrbs2d_.c
    src/itrrv2d_.c
    src/itrsd2d_.c
    src/kbrid_.c
    src/kbsid_.c
    src/krecvid_.c
    src/ksendid_.c
    src/sgamn2d_.c
    src/sgamx2d_.c
    src/sgebr2d_.c
    src/sgebs2d_.c
    src/sgerv2d_.c
    src/sgesd2d_.c
    src/sgsum2d_.c
    src/strbr2d_.c
    src/strbs2d_.c
    src/strrv2d_.c
    src/strsd2d_.c
    src/sys2blacs_.c
    src/ygamn2d_.c
    src/ygamx2d_.c
    src/ygebr2d_.c
    src/ygebs2d_.c
    src/ygerv2d_.c
    src/ygesd2d_.c
    src/ygsum2d_.c
    src/ytrbr2d_.c
    src/ytrbs2d_.c
    src/ytrrv2d_.c
    src/ytrsd2d_.c
)

set(blacs_LANGUAGE c)
