set(blas_COMMON_SOURCES
    
)

set(blas_PRECISION_SOURCES
    src/easum.f
    src/eaxpy.f
    src/ecabs1.f
    src/ecopy.f
    src/edot.f
    src/egbmv.f
    src/egemm.f
    src/egemmtr.f
    src/egemv.f
    src/eger.f
    src/enrm2.f90
    src/erot.f
    src/erotg.f90
    src/erotm.f
    src/erotmg.f
    src/esbmv.f
    src/escal.f
    src/espmv.f
    src/espr.f
    src/espr2.f
    src/eswap.f
    src/esymm.f
    src/esymv.f
    src/esyr.f
    src/esyr2.f
    src/esyr2k.f
    src/esyrk.f
    src/etbmv.f
    src/etbsv.f
    src/etpmv.f
    src/etpsv.f
    src/etrmm.f
    src/etrmv.f
    src/etrsm.f
    src/etrsv.f
    src/eyasum.f
    src/eynrm2.f90
    src/ieamax.f
    src/iyamax.f
    src/yaxpy.f
    src/ycopy.f
    src/ydotc.f
    src/ydotu.f
    src/yerot.f
    src/yescal.f
    src/ygbmv.f
    src/ygemm.f
    src/ygemmtr.f
    src/ygemv.f
    src/ygerc.f
    src/ygeru.f
    src/yhbmv.f
    src/yhemm.f
    src/yhemv.f
    src/yher.f
    src/yher2.f
    src/yher2k.f
    src/yherk.f
    src/yhpmv.f
    src/yhpr.f
    src/yhpr2.f
    src/yrotg.f90
    src/yscal.f
    src/yswap.f
    src/ysymm.f
    src/ysyr2k.f
    src/ysyrk.f
    src/ytbmv.f
    src/ytbsv.f
    src/ytpmv.f
    src/ytpsv.f
    src/ytrmm.f
    src/ytrmv.f
    src/ytrsm.f
    src/ytrsv.f
)

set(blas_DUAL_INTERFACE_SOURCES
    
)

set(blas_LANGUAGE fortran)
